//go:build !ignore_autogenerated

/*
Copyright 2024.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupAccess) DeepCopyInto(out *ClusterGroupAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupAccess.
func (in *ClusterGroupAccess) DeepCopy() *ClusterGroupAccess {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGroupAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupAccessList) DeepCopyInto(out *ClusterGroupAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGroupAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupAccessList.
func (in *ClusterGroupAccessList) DeepCopy() *ClusterGroupAccessList {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGroupAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupAccessSpec) DeepCopyInto(out *ClusterGroupAccessSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]ClusterUserDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]GroupAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailableGroups != nil {
		in, out := &in.AvailableGroups, &out.AvailableGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupAccessSpec.
func (in *ClusterGroupAccessSpec) DeepCopy() *ClusterGroupAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupAccessStatus) DeepCopyInto(out *ClusterGroupAccessStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupAccessStatus.
func (in *ClusterGroupAccessStatus) DeepCopy() *ClusterGroupAccessStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGroupRequest) DeepCopyInto(out *ClusterGroupRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGroupRequest.
func (in *ClusterGroupRequest) DeepCopy() *ClusterGroupRequest {
	if in == nil {
		return nil
	}
	out := new(ClusterGroupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterUserDefinition) DeepCopyInto(out *ClusterUserDefinition) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterUserDefinition.
func (in *ClusterUserDefinition) DeepCopy() *ClusterUserDefinition {
	if in == nil {
		return nil
	}
	out := new(ClusterUserDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupAccessRequest) DeepCopyInto(out *GroupAccessRequest) {
	*out = *in
	in.ForUser.DeepCopyInto(&out.ForUser)
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupAccessRequest.
func (in *GroupAccessRequest) DeepCopy() *GroupAccessRequest {
	if in == nil {
		return nil
	}
	out := new(GroupAccessRequest)
	in.DeepCopyInto(out)
	return out
}
